### ISSUE TITLE
variable capture parsed incorretly by haproxy-frontend.cfg.j2

### ISSUE THREAD

**Issue by forrayz** [uoi-io/ansible-haproxy#18]
If variable capture defined like this in frontend section

```yml
haproxy_frontend:
  - www.foo-bar.com_cluster:
      mode: http
      binds_ssl:
        - 192.168.17.103:443 ssl crt /home/haproxy/certs/www.foo-bar.com.pem
      capture: request  header Host len 20
```
thsi will produce the following in haproxy.cfg

```
capture: r
capture: e
capture: q
capture: u
.
.
.

```
each charater wil be a variable called capture validation than fails.

As a workaround i have modifyed haproxy-frontend.cfg.j2 not to have the for cycle

from:

```j2
{% if value.capture is defined %}
                {% for cap in value.capture %}
    capture         {{ cap }}
                {% endfor %}
            {% endif %}
```

TO:
```j2
        {% if value.capture is defined %}
    capture         {{ value.capture }}
            {% endif %}

            {% if value.capture1 is defined %}
    capture         {{ value.capture1 }}
            {% endif %}
            {% if value.capture2 is defined %}
    capture         {{ value.capture2 }}
            {% endif %}
    
            {% if value.capture3 is defined %}
    capture         {{ value.capture3 }}
            {% endif %}
```
to allow four capture variable / frontend
