### ISSUE TITLE
Support "option" in STATS section

### ISSUE THREAD

**Issue by haydenseitz** [uoi-io/ansible-haproxy#45]
Is there any way to pass "option" parameters in the STATS section? Below is an example use case to mute logging from the stats dashboard:

```
listen stats
    bind       *:8080
    mode       http
    maxconn    10
    stats      enable
    stats      admin if TRUE
    stats      refresh 10s
    stats      show-legends
    stats      show-node
    stats      hide-version
    stats      uri /
    option     dontlog-normal      <---
    timeout    client 100s
    timeout    server 100s
    timeout    connect 100s
    timeout    queue 100s
```

**Comment by goldyfruit** [comment]
Hi @haydenseitz 

~~Yes, as documented in the `README` _(in the `stats` section)_, you could use the `haproxy_stats_options` variable to set a list of options.~~
```
haproxy_stats_options:
  - dontlog-normal
```

#### EDIT

After checking, the `haproxy_stats_options` parameter will only add `stats` options. There is currently no way to add `option` to the `stats` listrener.

Here is the template: https://github.com/uoi-io/ansible-haproxy/blob/master/templates/etc/haproxy/haproxy-stats.cfg.j2

**Comment by haydenseitz** [comment]
I was going to submit a PR to add that functionality, but I was able to set up a stats page with options using `haproxy_frontend`:
```
haproxy_stats: false
haproxy_frontend:
  - stats:
      binds:
        - :9001
      stats:
        - enable
        - refresh 10s
        - show-legends
        - show-node
        - hide-version
        - uri /
      options:
        - dontlog-normal
```
